#!/bin/bash

set -euo pipefail

## Functions

generate_uefi_keys() {
  mkdir -p "$UEFI_KEYS_DIR"

  cd "$UEFI_KEYS_DIR"

  GUID="$(uuidgen --random)"
  echo "$GUID" > guid.txt

  echo "Generating the UEFI Secure Boot keys"
  read -p "Enter a Common Name: " NAME

  echo "Create Platform key..."
  openssl req -newkey rsa:4096 -nodes -keyout PK.key -new -x509 -sha256 -days 3650 \
              -subj "/CN=$NAME Platform Key/" -out PK.crt
  openssl x509 -outform DER -in PK.crt -out PK.cer
  cert-to-efi-sig-list -g $GUID PK.crt PK.esl
  sign-efi-sig-list -k PK.key -c PK.crt PK PK.esl PK.auth
  sign-efi-sig-list -c PK.crt -k PK.key PK /dev/null PK_null.auth

  echo "Create Key Exchange key..."
  openssl req -newkey rsa:4096 -nodes -keyout KEK.key -new -x509 -sha256 -days 3650 \
              -subj "/CN=$NAME Key Exchange Key/" -out KEK.crt
  openssl x509 -outform DER -in KEK.crt -out KEK.cer
  cert-to-efi-sig-list -g $GUID KEK.crt KEK.esl

  echo "Create signature database key..."
  openssl req -newkey rsa:4096 -nodes -keyout db.key -new -x509 -sha256 -days 3650 \
              -subj "/CN=$NAME Signature Database key/" -out db.crt
  openssl x509 -outform DER -in db.crt -out db.cer
  cert-to-efi-sig-list -g $GUID db.crt db.esl

  chmod 0400 *.{key,auth}
  echo "UEFI Secure Boot keys are created under '$UEFI_KEYS_DIR'."
}

enroll_uefi_keys() {
  cd "$UEFI_KEYS_DIR"

  echo "Enrolling Secure Boot keys in UEFI firmware"
  efi-updatevar -e -f KEK.esl KEK
  efi-updatevar -e -f db.esl db
  efi-updatevar -f PK.auth PK
  echo "Secure Boot keys in '$UEFI_KEYS_DIR' are registered."
}

sign_uefi_keys() {
  cd "$UEFI_KEYS_DIR"

  echo "Signing GRUB boot loader with UEFI Secure Boot keys"

  grub-mkconfig -o "$BOOT_DIR/grub/grub.cfg"
  grub-install --target=x86_64-efi --boot-directory="$BOOT_DIR" --efi-directory="$EFI_DIR" --bootloader-id="$UEFI_ID_GRUB"

  sbsign --key db.key --cert db.crt --output "$EFI_DIR/$UEFI_PATH_GRUB" "$EFI_DIR/$UEFI_PATH_GRUB"
  echo "GRUB boot loader is signed with UEFI Secure Boot keys."
}

verify_signatures() {
  echo "List the signatures in boot loader"
  sbverify --list "$EFI_DIR/$UEFI_PATH_GRUB"

  echo "Verifying the signature with UEFI keys"
  cd "$UEFI_KEYS_DIR"
  sbverify --cert db.crt "$EFI_DIR/$UEFI_PATH_GRUB"
}

list_uefi_keys() {
  echo "Listing the secure boot keys enrolled in firmware"
  efi-readvar
}

encrypt_partition_tpm2() {

  echo "Create random key file"
  dd if=/dev/random of=/etc/secret.bin bs=32 count=1

  echo "Add the key from file to '$TPM2_DEV' partition"
  cryptsetup luksAddKey $TPM2_DEV /etc/secret.bin

  echo "Note that you may need to reset your TPM from the BIOS setup page"
  sleep 2

  echo "Add key to TPM"

  echo "Run tpm2_createpolicy"
  tpm2_createpolicy --policy-pcr -l sha1:0,2,4,7 -L policy.digest
  echo "======="
  sleep 2
  echo "Run tpm2_createprimary"
  tpm2_createprimary -C e -g sha1 -G rsa -c primary.context
  echo "======="
  sleep 2
  echo "Run tpm2_create"
  tpm2_create -g sha256 -u obj.pub -r obj.priv -C primary.context -L policy.digest -a "noda|adminwithpolicy|fixedparent|fixedtpm" -i /etc/secret.bin
  echo "======="
  sleep 2
  echo "Run tpm2_load"
  tpm2_load -C primary.context -u obj.pub -r obj.priv -c load.context
  echo "======="
  sleep 2
  echo "Run tpm2_evictcontrol"
  tpm2_evictcontrol -C o -c load.context 0x81000000
  echo "======="
  sleep 2
  rm load.context obj.priv obj.pub policy.digest primary.context

  echo "check whether the key is successfully added in TPM"
  tpm2_getcap handles-persistent
  tpm2_readpublic -c 0x81000000

  echo "print the key stored in TPM"
  tpm2_unseal -c 0x81000000 -p pcr:sha1:0,2,4,7 -o /tmp/secret

  echo "Compare the created key and TPM key"
  echo "=================================="
  sha1sum /etc/secret.bin
  sha1sum /tmp/secret
  echo "=================================="

}

## Main

SB_CONFIG_FILE="/etc/secureboot.conf"


if [ -r "$SB_CONFIG_FILE" ]; then
  . "$SB_CONFIG_FILE"
else
  echo "Failed to read the secureboot configuration file '$SB_CONFIG_FILE'"
  exit 1
fi


case "$1" in
  generate-keys)
    generate_uefi_keys;
    ;;
  enroll-keys)
    enroll_uefi_keys;
    ;;
  sign-keys)
    sign_uefi_keys;
    ;;
  verify-bootloader)
    verify_signatures;
    ;;
  list-keys)
    list_uefi_keys;
    ;;
  tpm2-luks)
    encrypt_partition_tpm2;
    ;;
  *)
    echo
    echo "commands:"
    echo "  generate-keys       Generate the UEFI Secure Boot keys"
    echo "  enroll-keys         Enrolling secure boot keys in UEFI firmware"
    echo "  sign-keys           Signing the boot loader with secure boot keys"
    echo "  verify-bootloader   Verify the signed boot loader"
    echo "  list-keys           List all the secure boot keys enrolled in UEFI firmware"
    echo "  tpm2-luks           Encrypt partition using TPM 2.0"
    ;;
esac
